ALTER TABLE Event ADD COLUMN DeletedMark INTEGER NOT NULL DEFAULT 0;
ALTER TABLE MonthEvent ADD COLUMN DeletedMark INTEGER NOT NULL DEFAULT 0;
ALTER TABLE CashRegisterWorkingShift ADD COLUMN DeletedMark INTEGER NOT NULL DEFAULT 0;
ALTER TABLE TicketEventBase ADD COLUMN DeletedMark INTEGER NOT NULL DEFAULT 0;
ALTER TABLE UpdateEvent ADD COLUMN DeletedMark INTEGER NOT NULL DEFAULT 0;
