ALTER TABLE CPPKTicketControl ADD COLUMN Trips7000Spend INTEGER  DEFAULT NULL;
ALTER TABLE CPPKTicketControl ADD COLUMN TripsCount INTEGER  DEFAULT NULL;
ALTER TABLE CPPKTicketControl ADD COLUMN Trips7000Count INTEGER  DEFAULT NULL;