/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_ppr_kuznyechik_NativeCppcryptoKuznyechik */

#ifndef _Included_ru_ppr_kuznyechik_NativeCppcryptoKuznyechik
#define _Included_ru_ppr_kuznyechik_NativeCppcryptoKuznyechik
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_ppr_kuznyechik_NativeCppcryptoKuznyechik
 * Method:    init
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_ppr_kuznyechik_NativeCppcryptoKuznyechik_init
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     ru_ppr_kuznyechik_NativeCppcryptoKuznyechik
 * Method:    encryptBlock
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_ru_ppr_kuznyechik_NativeCppcryptoKuznyechik_encryptBlock
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     ru_ppr_kuznyechik_NativeCppcryptoKuznyechik
 * Method:    decryptBlock
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_ru_ppr_kuznyechik_NativeCppcryptoKuznyechik_decryptBlock
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     ru_ppr_kuznyechik_NativeCppcryptoKuznyechik
 * Method:    omac1
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_ru_ppr_kuznyechik_NativeCppcryptoKuznyechik_omac1
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
